name: decoder_qr_code_pix
description: A decoder dynamic QrCode pix  
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  pretty_json: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
